module Elektron.Digitakt.CppStructs exposing (..)

{-| Sizes and offsets of fields in the C++ data structures

Each function gives the offset to a particular field, or the size of a
structure.

These functions are generated by a utility program, using the C++ header files
that define the storage formats from Elektron. Unfortunately, those header
files are not openly available. If you need another field added here, ask
Mark for it, and he can generate it for you.

-}

patternStorage_kitIndex : Int -> Maybe Int
patternStorage_kitIndex v = case v of
  0 -> Just 22896
  1 -> Just 24944
  2 -> Just 24944
  3 -> Just 24976
  4 -> Just 24976
  5 -> Just 24976
  6 -> Just 24976
  7 -> Just 24992
  8 -> Just 24992
  9 -> Just 25008
  _ -> Nothing


patternStorage_sizeof : Int -> Maybe Int
patternStorage_sizeof v = case v of
  0 -> Just 23040
  1 -> Just 25088
  2 -> Just 25088
  3 -> Just 25088
  4 -> Just 25088
  5 -> Just 25088
  6 -> Just 25088
  7 -> Just 25088
  8 -> Just 25088
  9 -> Just 25088
  _ -> Nothing


trackStorage_soundSlotLocks : Int -> Maybe Int
trackStorage_soundSlotLocks v = case v of
  1 -> Just 832
  2 -> Just 832
  3 -> Just 832
  4 -> Just 832
  5 -> Just 832
  _ -> Nothing


trackStorage_sizeof : Int -> Maybe Int
trackStorage_sizeof v = case v of
  0 -> Just 779
  1 -> Just 907
  2 -> Just 909
  3 -> Just 909
  4 -> Just 910
  5 -> Just 911
  _ -> Nothing



kitStorage_trackSounds : Int -> Maybe Int
kitStorage_trackSounds v = case v of
  0 -> Just 36
  1 -> Just 36
  2 -> Just 36
  3 -> Just 36
  4 -> Just 36
  5 -> Just 36
  6 -> Just 36
  7 -> Just 36
  8 -> Just 36
  9 -> Just 36
  _ -> Nothing


kitStorage_midiParams : Int -> Maybe Int
kitStorage_midiParams v = case v of
  0 -> Just 1424
  1 -> Just 1424
  2 -> Just 1424
  3 -> Just 1424
  4 -> Just 1424
  5 -> Just 1424
  6 -> Just 1424
  7 -> Just 1424
  8 -> Just 1424
  9 -> Just 1424
  _ -> Nothing


kitStorage_sizeof : Int -> Maybe Int
kitStorage_sizeof v = case v of
  0 -> Just 2560
  1 -> Just 2560
  2 -> Just 2560
  3 -> Just 2560
  4 -> Just 2560
  5 -> Just 2560
  6 -> Just 2560
  7 -> Just 2560
  8 -> Just 2560
  9 -> Just 2560
  _ -> Nothing


midiSetupStorage_enableMask : Int -> Maybe Int
midiSetupStorage_enableMask v = case v of
  0 -> Just 100
  1 -> Just 100
  _ -> Nothing


midiSetupStorage_sizeof : Int -> Maybe Int
midiSetupStorage_sizeof v = case v of
  0 -> Just 108
  1 -> Just 108
  _ -> Nothing


soundStorage_sampleSlot : Int -> Maybe Int
soundStorage_sampleSlot v = case v of
  0 -> Just 52
  1 -> Just 68
  2 -> Just 68
  _ -> Nothing


soundStorage_sampleFile : Int -> Maybe Int
soundStorage_sampleFile v = case v of
  0 -> Just 132
  1 -> Just 132
  2 -> Just 132
  _ -> Nothing


soundStorage_sizeof : Int -> Maybe Int
soundStorage_sizeof v = case v of
  0 -> Just 160
  1 -> Just 160
  2 -> Just 160
  _ -> Nothing


soundParameters_sampleParamId : Int -> Maybe Int
soundParameters_sampleParamId v = case v of
  0 -> Just 12
  1 -> Just 20
  2 -> Just 20
  _ -> Nothing


projectSettingsStorage_sampleList : Int -> Maybe Int
projectSettingsStorage_sampleList v = case v of
  0 -> Just 69
  1 -> Just 70
  2 -> Just 70
  3 -> Just 70
  4 -> Just 70
  5 -> Just 70
  6 -> Just 70
  7 -> Just 70
  _ -> Nothing


projectSettingsStorage_sizeof : Int -> Maybe Int
projectSettingsStorage_sizeof v = case v of
  0 -> Just 2560
  1 -> Just 2560
  2 -> Just 2560
  3 -> Just 2560
  4 -> Just 2560
  5 -> Just 2560
  6 -> Just 2560
  7 -> Just 2560
  _ -> Nothing